### PR TITLE
[WIP] Hardware accelerations to lighting and others

### PR DESCRIPTION
**Pull request by ishland**
- [x] Lighting API

- [x] OpenCL basic things

- [x] Gracefully recover from failing to init device and remove it from use

- [x] Cache Buffers

- [ ] Implement ishland's lighting algorithm

### CODE REVIEW

**Comment by krolik-exe** [comment]
When i try to run server with the OpenCL patch , it crashes

my cpu and gpu support opencl version 1.2

**Comment by Titaniumtown** [comment]
@krolik-exe Some more info like what gpu it is, what OS, what drivers, etc, would be useful.

**Comment by krolik-exe** [comment]
Intel Graphics 4600 , Windows 10 64 Bit - build 19041.572 (2004) , latest drivers from intel website - 20.19.15.5144 , cpu- Intel Core i7 4790k

**Comment by duplexsystem** [comment]
we need logs

**Comment by krolik-exe** [comment]
[latest.log](https://github.com/YatopiaMC/Yatopia/files/5403060/latest.log)

**Comment by krolik-exe** [comment]
There is the latest log

**Comment by duplexsystem** [comment]
Is that the full log

**Comment by Titaniumtown** [comment]
Doesn't seem like it lol.

**Comment by krolik-exe** [comment]
> Is that the full log

Unfortunately , yes

**Comment by krolik-exe** [comment]
This is what doesn’t show on logs but only on console

911857EF-65B2-489F-B600-F05DABBBC4BB

**Comment by krolik-exe** [comment]
I’m using jdk 15

**Comment by krolik-exe** [comment]
I will test on Java 8 tomorrow and see if the issue still persists but for now i will test JDK 11

**Comment by krolik-exe** [comment]
JDK 11 still the same

**Comment by Titaniumtown** [comment]
@krolik-exe can you please copy what is in your console into pastebin?

**Comment by duplexsystem** [comment]
@krolik-exe can you try again with latest build

**Comment by krolik-exe** [comment]
I still have an error , but this time different


System Info: Java 15 (OpenJDK 64-Bit Server VM 15+36) Host: Windows 10 10.0 (amd64)
Loading libraries, please wait...
[19:08:47 INFO]: [net.yatopia.server.opencl.OpenCompute] Initializing OpenCL...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jogamp.common.os.NativeLibrary$3 (file:/C:/Tofikowy/cache/patched_1.16.3.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of com.jogamp.common.os.NativeLibrary$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[19:08:48 INFO]: [net.yatopia.server.opencl.OpenCompute] Found 2 devices
[19:08:48 INFO]: [net.yatopia.server.opencl.OpenCompute] Device 0: Intel(R) HD Graphics 4600
[19:08:48 INFO]: [net.yatopia.server.opencl.OpenCompute] Device 1: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
[19:08:48 INFO]: [net.yatopia.server.opencl.OpenCompute] No overrides defined, sorting devices by benchmark results...
[19:08:48 INFO]: [net.yatopia.server.opencl.OpenCompute] Failed to initialize Intel(R) HD Graphics 4600
Exception in thread "YatopiaCL-0" java.lang.NullPointerException: Cannot invoke "com.jogamp.opencl.CLCommandQueue.put1DRangeKernel(com.jogamp.opencl.CLKernel, long, long, long, com.jogamp.opencl.CLEventList)" because "clCommandQueue" is null
        at net.yatopia.server.opencl.BasicOpenCLBenchmark.lambda$benchmark$0(BasicOpenCLBenchmark.java:69)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)

**Pull request closed without merging**
