### PR TITLE
Add Hydrinity Patches and Lithium Gen Patches & Some Purpur Patches & Custom Locale

### PR DESCRIPTION
**Pull request by duplexsystem**
This is a **MEGA BIG BOI PR**

### CODE REVIEW

**Comment by Titaniumtown** [comment]
Since you've added the infinity bow config patches from purpur, would it also be fitting for 0136-Allow-infinite-and-mending-enchantments-together.patch to be ported from purpur as well since they sorta change mending/infinity mechanics? Of course you're doing all this work for free, so no rush :)

**Comment by duplexsystem** [comment]
I'll think about it. I was asked by a friend do add infinity with no arrows and I figured I'd add it along side Purpur's patch.

**Comment by Titaniumtown** [comment]
@budgidiere ok, got it! :)

**Review by PhantomG27249 — APPROVED** [review]
So far seems to be good from my testing, didn't see any differences in world gen in any dimensions and chunk generation was noticeably quicker.

**Review by MrIvanPlays — CHANGES_REQUESTED** [review]
Blocking until I can review properly

**Review by ishland — COMMENTED** [review]
Seems fine for me with the code. However, I currently don't have time to test these changes.

**Review by MrIvanPlays — CHANGES_REQUESTED** [review]
Very skeptical about the noise patches. Also that they're still present in the patches/removed
When you add patches too, add them as last, except if you need that patch in a patch that is already existing.

**Comment by duplexsystem** [comment]
I all of them as last but Utilities because that, by design, goes towards the top of the patch list.

**Comment by duplexsystem** [comment]
@MrIvanPlays do you have any further objections?

**Comment by MrIvanPlays** [comment]
wait im testing it rn

**Comment by duplexsystem** [comment]
Not merging yet just asking if you do

**Review by MrIvanPlays — APPROVED** [review]
All seems good

**Comment by duplexsystem** [comment]
@nkomarn Thoughts?

**Comment by Titaniumtown** [comment]
I can test this PR right now! :) I'll make a comment if something goes wrong.

**Comment by duplexsystem** [comment]
Also make a comment if nothing goes wrong

**Comment by toinouH** [comment]
@Titaniumtown Please do it ^^

**Comment by Titaniumtown** [comment]
ok! I'll keep you guys posted! :)

**Comment by Titaniumtown** [comment]
everything seems to work without any issues. LGTM

**Comment by Titaniumtown** [comment]
Are there any reasons not to merge the PR?

**Comment by duplexsystem** [comment]
yes we're wait on some feed back on a final change

**Comment by toinouH** [comment]
`[19:15:38] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_16_R2.ReportedException: Exception ticking world
	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1446) ~[patched_1.16.3.jar:git-Yatopia-"27ee620"]
	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:391) ~[patched_1.16.3.jar:git-Yatopia-"27ee620"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1278) ~[patched_1.16.3.jar:git-Yatopia-"27ee620"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1009) ~[patched_1.16.3.jar:git-Yatopia-"27ee620"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.3.jar:git-Yatopia-"27ee620"]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalArgumentException: Cannot get property BlockStateInteger{name=level, clazz=class java.lang.Integer, values=[0, 1, 2, 3]} as it does not exist in Block{minecraft:air}
	at net.minecraft.server.v1_16_R2.IBlockDataHolder.get(IBlockDataHolder.java:95) ~[patched_1.16.3.jar:git-Yatopia-"27ee620"]
	at net.minecraft.server.v1_16_R2.BlockCauldron.c(BlockCauldron.java:238) ~[patched_1.16.3.jar:git-Yatopia-"27ee620"]
	at net.minecraft.server.v1_16_R2.WorldServer.a(WorldServer.java:1100) ~[patched_1.16.3.jar:git-Yatopia-"27ee620"]
	at net.minecraft.server.v1_16_R2.ChunkProviderServer.tickChunks(ChunkProviderServer.java:1034) ~[patched_1.16.3.jar:git-Yatopia-"27ee620"]
	at net.minecraft.server.v1_16_R2.ChunkProviderServer.tick(ChunkProviderServer.java:926) ~[patched_1.16.3.jar:git-Yatopia-"27ee620"]
	at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:888) ~[patched_1.16.3.jar:git-Yatopia-"27ee620"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1430) ~[patched_1.16.3.jar:git-Yatopia-"27ee620"]
	... 5 more
[19:15:38] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.IllegalArgumentException: Cannot get property BlockStateInteger{name=level, clazz=class java.lang.Integer, values=[0, 1, 2, 3]} as it does not exist in Block{minecraft:air}
	at net.minecraft.server.v1_16_R2.IBlockDataHolder.get(IBlockDataHolder.java:95) ~[patched_1.16.3.jar:git-Yatopia-"27ee620"]
	at net.minecraft.server.v1_16_R2.BlockCauldron.c(BlockCauldron.java:238) ~[patched_1.16.3.jar:git-Yatopia-"27ee620"]
	at net.minecraft.server.v1_16_R2.WorldServer.a(WorldServer.java:1100) ~[patched_1.16.3.jar:git-Yatopia-"27ee620"]
	at net.minecraft.server.v1_16_R2.ChunkProviderServer.tickChunks(ChunkProviderServer.java:1034) ~[patched_1.16.3.jar:git-Yatopia-"27ee620"]
	at net.minecraft.server.v1_16_R2.ChunkProviderServer.tick(ChunkProviderServer.java:926) ~[patched_1.16.3.jar:git-Yatopia-"27ee620"]
	at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:888) ~[patched_1.16.3.jar:git-Yatopia-"27ee620"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1430) ~[patched_1.16.3.jar:git-Yatopia-"27ee620"]
	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:391) ~[patched_1.16.3.jar:git-Yatopia-"27ee620"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1278) ~[patched_1.16.3.jar:git-Yatopia-"27ee620"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1009) ~[patched_1.16.3.jar:git-Yatopia-"27ee620"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.3.jar:git-Yatopia-"27ee620"]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[19:15:38] [Server thread/ERROR]: This crash report has been saved to: /server/0e714bff-6f8f-43c1-86d2-cb0cabb122b0/./crash-reports/crash-2020-10-26_19.15.38-server.txt
[19:15:38] [Server thread/INFO]: Stopping server`

**Comment by duplexsystem** [comment]
That may or may not be related to this PR.

**Comment by MrIvanPlays** [comment]
I searched and either `27ee620` is a really old yatopia version or someone custom built it.

EDIT: latest info; looks like commit hashes are out of sync for some reason. this is this build so we're gonna investigate

**Comment by Titaniumtown** [comment]
I've build the PR and currently have it running rn w/o any issues. so idk how @toinouH got that error.

**Comment by toinouH** [comment]
@Titaniumtown this is from someone in the #bigServers channel but we might had a confusion in the conversation

**Comment by Titaniumtown** [comment]
@toinouH #bigServers channel? What channel? I don't see that on the discord.

**Comment by duplexsystem** [comment]
We've verified that `27ee620` is the correct build id.

**Comment by duplexsystem** [comment]
PR on hold until todo list complete:

- [ ] Find source of crash and fix

- [x] Check Terrain gen against vanilla

- [ ] Find and Fix Mem leak

**Comment by duplexsystem** [comment]
@Titaniumtown you can speed this up by comparing terrain against vanilla (post pictures)

**Comment by Titaniumtown** [comment]
@budgidiere If I have time, I will definitely do that, but currently I don't. I'll keep you posted on my availability.

**Comment by duplexsystem** [comment]
We've found some major issues internally. PR is on hold until they are fixed.

**Comment by Titaniumtown** [comment]
Ok, I'll try to fit it in ASAP when I get the time! :)

**Comment by Titaniumtown** [comment]
@budgidiere I did the testing, the terrain gen is different:
seed: 3472445692505646235
Spawn without the PR:
without PR

Spawn with the PR:
With PR

**Comment by MrIvanPlays** [comment]
> @budgidiere I did the testing, the terrain gen is different:
> seed: 3472445692505646235
> Spawn without the PR:
> without PR
> 
> Spawn with the PR:
> With PR

yeh we already discovered that

**Comment by Titaniumtown** [comment]
@MrIvanPlays well @budgidiere told me to test it, so I did lol.

**Comment by Titaniumtown** [comment]
I can test the latest commit once I'm done compiling it.

**Comment by Titaniumtown** [comment]
@budgidiere The PR works now!
seed: 3472445692505646235
Spawn without the PR:
without PR

Spawn with fix:
with fix

Previous spawn before fix:
With PR

**Comment by duplexsystem** [comment]
All generation seems fine to me and the same as vanilla. PR is ready for merge.

**Pull request merged**
