### PR TITLE
chmod +x scripts/*.sh

### PR DESCRIPTION
**Pull request by Titaniumtown**
does what the title says.

### CODE REVIEW

**Comment by MrIvanPlays** [comment]
what why

**Comment by Titaniumtown** [comment]
@MrIvanPlays Because you have to do it manually when you first clone, if you don't running anything that references a script in `scripts` fails because it's not marked as executable.

**Comment by MrIvanPlays** [comment]
ok but the diff shows its not all the scripts

**Comment by Titaniumtown** [comment]
Yea, only those scripts aren't marked as executable.

**Comment by nkomarn** [comment]
This should be merged. Every time I pull the Yatopia repo, I have to chmod the scripts to be able to set up a dev environment.

**Pull request merged**
