### PR TITLE
Highly optimize VillagePlace filtering, take 2

### PR DESCRIPTION
**Pull request by MrIvanPlays**
bgidiere I FORBID you to merge this pull request until I say so.

Fixes villager weirdness we had in the previous version.

### CODE REVIEW

**Comment by duplexsystem** [comment]
I cast disspell on your forbid spell

**Comment by toinouH** [comment]
I feel like I'm going to take back my grimoire of black magic :P

**Comment by MrIvanPlays** [comment]
I ban you @budgidiere from interacting with yatopiamc repositories for 7 days
( :eyes: :kappa: )

**Comment by duplexsystem** [comment]
I cast disspell on your ban.

**Comment by MrIvanPlays** [comment]
> I cast disspell on your ban.

w8. thats illegal

**Pull request closed without merging**
