### PR TITLE
More Exp More Optimization

### PR DESCRIPTION
**Pull request by duplexsystem**

### CODE REVIEW

**Comment by Titaniumtown** [comment]
Seems to be slower with chunk generation:
Screenshot from 2020-08-09 14-09-33

**Comment by duplexsystem** [comment]
Can you reset master to make sure this is not margin or error or something.

**Comment by y6x2digc** [comment]
@Titaniumtown How do you do Benchmark?

**Comment by Titaniumtown** [comment]
Chunk generation. Just pregen like 2k.

**Comment by tr7zw** [comment]
I don't think having a patch that is 32k lines long is any good. This is not really maintainable and unstable for all patches applied after it.

**Comment by duplexsystem** [comment]
The point is that it's the final patch and should be deleted before working with the project and then regenerated. Doesn't matter of there are ever any merge conflicts because you just regen the patch.

**Pull request closed without merging**
