### PR TITLE
Fix some brokenness when using on windows computers with spaces…

### PR DESCRIPTION
**Pull request by duplexsystem**
… in the cloned path.

### CODE REVIEW

**Comment by duplexsystem** [comment]
I'm still making sure everything works. Don't merge for now.

**Comment by duplexsystem** [comment]
I'm making sure the changes match up with upstream

**Comment by duplexsystem** [comment]
These are the only changes that I have found that match upstream. If you want I can go through and fix all the brokenness.

**Comment by tr7zw** [comment]
Uhm the master branch is the wrong branch to merge that into. The correct branches are the dev/ver/1.16.1 which will replace the master soonish and the ver/1.15.2 which is in maintanance mode.

**Comment by duplexsystem** [comment]
K I'll fix that in a bit.

**Pull request closed without merging**
