### PR TITLE
Entity tracker optimizations

### PR DESCRIPTION
**Pull request by nkomarn**
I plan to implement a working async entity tracker as well as implement additional general tracker optimizations.

Currently, PlayerVelocityEvent is called async and causes tons of errors. Additionally, Citizens refuses to load with this patch. I will be investigating these in the near future.

### CODE REVIEW

**Review by MrIvanPlays — APPROVED** [review]

**Review by duplexsystem — APPROVED** [review]
Looks good.

**Review by PhantomG27249 — APPROVED** [review]
Seems fine from my testing yet to find any issues with it and helps entity lag a lot

**Comment by nkomarn** [comment]
I will put this patch on my server in a bit to give it a real-world test. We can merge if I don't encounter any issues.

**Review by duplexsystem — APPROVED** [review]

**Comment by duplexsystem** [comment]
Merging in 24hrs unless there are no objections.

**Comment by nkomarn** [comment]
> Merging in 24hrs unless there are no objections.

Fine by me. Seems stable from my tests on a production server.

**Comment by duplexsystem** [comment]
Never mind merge now.

**Pull request merged**
