### PR TITLE
Update NBT API (1.16.1)

### PR DESCRIPTION
**Pull request by SoSeDiK**

### CODE REVIEW

**Comment by MrIvanPlays** [comment]
Not too sure about it for 1.16.1

**Comment by SoSeDiK** [comment]
> Not too sure about it for 1.16.1

This version also has new API features besides 1.16.2 support.
Since 1.16.2 is still in the testing stage, and many (including me) use the 1.16.1 branch on production servers, I made a separate PR.
It'll remove a message about an outdated build upon starting a server as well.

**Comment by MrIvanPlays** [comment]
> It'll remove a message about an outdated build upon starting a server as well.

we already have newer builds for 1.16.1. update
as for nbt-api im not sure why we need to update it as new features aren't planned for 1.16.1

**Comment by SoSeDiK** [comment]
I meant NBT API's message about up to date version, not the core itself.
Well, it's up to you. I would not really call it a new feature, just a "*dependency*" update.

**Comment by MrIvanPlays** [comment]
You say NBT api has new features, which means updating it in yatopia also means new features in yatopia 
as I said, 1.16.1 new features aren't planned.

**Comment by SoSeDiK** [comment]
I'd kind of argue with this.
You hardly do any changes to Yatopia, just bump the plugin's version which is outdated right now.
It even prints out a warning about it when starting a server:
```
[NBTAPI] The NBT-API at 'package de.tr7zw.nbtapi, Bukkit, version unknown' seems to be outdated!
[NBTAPI] Current Version: '2.4.1' Newest Version: 2.5.0
[NBTAPI] Please update the nbt-api or the plugin that contains the api!
```
You can also take it as an upstream update, just for NBP API instead of a Paper fork.

**Comment by MrIvanPlays** [comment]
> You hardly do any changes to Yatopia, just bump the plugin's version which is outdated right now.



bruh

> You can also take it as an upstream update, just for NBP API instead of a Paper fork.

yes but for a version that doesn't plan on adding any new features doesn't need to update upstream. 
you can always ignore the warning.

**Comment by SoSeDiK** [comment]
> bruh

I'm talking about changes in this PR 😆

> yes but for a version that doesn't plan on adding any new features doesn't need to update upstream.
you can always ignore the warning.

My point is, if the 1.16.1 branch is still maintained (upstream updates/patches (#96)), I do not see any reason why updating NBT API would be a bad thing.

**Comment by MrIvanPlays** [comment]
> upstream updates

no we don't update upstream anymore there.

> patches (#96)

we ported these as hotfixes and thus are not new features. 

> I do not see any reason why updating NBT API would be a bad thing.

it is adding new api features and as I already said for 1.16.1 new features aren't planned.

**Comment by MrIvanPlays** [comment]
> I'm talking about changes in this PR 😆

You said "You hardly do any changes to Yatopia", fix your english please.

**Comment by SoSeDiK** [comment]
> we ported these as hotfixes and thus are not new features.

Sure, thank you for `Custom brand name`. My server was crashing without it 👍🏻

> You said "You hardly do any changes to Yatopia", fix your english please.

Don't take it literally. I thought it was obvious. Anyway, sorry for the misunderstanding, I'm not a native English speaker.

> it is adding new api features and as I already said for 1.16.1 new features aren't planned.

Again, you just update NBT API's version as Yatopia's library. It's a separate project. 1.16.1 is still in use among server owners. Everyone who decided to use Yatopia's shaded package instead of NBT API or shading it manually is now stuck with the outdated build.

**Comment by MrIvanPlays** [comment]
just because its an outdated build doesn't mean we have a solid reason to update it.
give me a solid reason why to update it except "1.16.2 is unstable and 1.16.1 is used more right now" and "it's outdated"

**Comment by SoSeDiK** [comment]
Why isn't it a reason in the first place?
Not everyone can use 1.16.2 as of now. And thus, you can't use newer NBT API features just because you decided to stick with Yatopia instead of using NBT API on your own.

**Comment by MrIvanPlays** [comment]
ok is there any stuff that can cause the server to break in the version currently compiled? no. only a warning. 
yes I do understand 1.16.2 is unstable, but still we're not adding new features to 1.16.1 .

**Comment by SoSeDiK** [comment]
You are prohibiting users from using newer NBT API just because they can't go 1.16.2 yet and decided to use Yatopia.
Would be nice to have a third opinion on this.

**Comment by MrIvanPlays** [comment]
im just tired of arguing, there have fun

**Pull request merged**
