### PR TITLE
Remove TIC-TACS from README.md

### PR DESCRIPTION
**Pull request by Titaniumtown**
I believe the tic-tacs patches were removed. So this shouldn't be in the README.md

### CODE REVIEW

**Comment by MrIvanPlays** [comment]
I'm 50/50 on this. 
While we currently _do not_ have any patches from tic-tacs, we may have in the future, which means this will need to be reput there, which will make messier git history.

**Comment by toinouH** [comment]
I have the same point of view of Ivan.

**Comment by katekerllenevich** [comment]
I would like to point out that continuing to have tic-tacs in the README is false advertising... so... :shrug:

**Comment by duplexsystem** [comment]
I agree, it's been too long, we've not readded the patch or any others from tic-tacs. We can always readd later.

**Pull request merged**
