### PR TITLE
[ci-skip] Updated Gradle to 7.0 

### PR DESCRIPTION
**Pull request by Toffikk**
### Changes

+ Updated to `Gradle 7.0`

+ Updated `shadow` to `7.0.0`

+ Added `.gitattributes` to fix issues with line endings

+ Updated `setup-java@v1` to `setup-java@v2`

+ Automatically set MC version of paperclip in GitHub Actions

+ Validate Gradle Wrapper and validate Gradle Distribution

+ Created new cache in GitHub Actions , because the old one was corrupted and was breaking some things

+ BIG Speed-Up in the compiling times (`around 10 or 20 minutes on WSL 2` (in my case it speeded up the build by `40+ minutes`, but this can vary between various computers/laptops)

+ Removed the `jcenter()` repository from `buildSrc` because of it being completely removed in `Gradle 8.0` (it's deprecated in `Gradle 7.0`) and it's complete shutdown is happening in February 2022

+ Supports building using `JDK 16`

+ Changed the `Default JVM OPTS` in `gradlew / gradlew.bat` and `jvmargs` in `gradle.properties` for more Speed-Up in build times (`-Xms1G -Xmx3G`)

+ ~~Removed the `org.gradle.configureondemand=true` from `gradle.properties` because I believe that it's not required and it also slows down the build times a bit~~ no longer, it actually speeds-up the build , my bad

+ Added `kotlin.parallel.tasks.in.project=true` to `gradle.properties` for faster and parallel kotlin tasks execution

+ Added the `org.gradle.caching=true` to `gradle.properties` for caching the build? and faster build times.

## !  IMPORTANT !

To compile using `JDK 16` , You need to update `Maven` to the latest version (currently `3.8.1`) because from my testing , `Maven 3.6.3` doesn't support `JDK 16` and just throws errors and then crashes.
-----------------------------------------------

### CODE REVIEW

**Comment by Toffikk** [comment]
Needed to create new cache because of it being corrupted , this fixes issues with `setup-java@v2` but still fails because of `Shadow` plugin on JDK 16

**Comment by snoopdoooggyttv** [comment]
Hi ! Shadow 7 is out!

[here](https://plugins.gradle.org/plugin/com.github.johnrengelman.shadow)

:shipit: :shipit: :shipit: :shipit:

**Comment by Titaniumtown** [comment]
java 16 just needs to be fixed. I'll look at the PR more tomorrow :)

**Comment by snoopdoooggyttv** [comment]
> java 16 just needs to be fixed. I'll look at the PR more tomorrow :)

Yes man! Shadow was the issue, 7 should resolve it ✔

**Comment by duplexsystem** [comment]
Let me review this before its merged

**Comment by duplexsystem** [comment]
Also how in the word does a build take 40+ minutes? What hardware are you running?

**Comment by Toffikk** [comment]
very overloaded pc always under pressure, 

but my hardware is

CPU: i7 7700k
GPU: RTX 2070 S
RAM: 16GB 3000 MHZ
JAVA: 16
OS: Windows 10 with wsl 2

it could take that much time , given that i have many programs open and i do many things in the same time , and my internet doesn't like me , but i somehow fixed it but i don't know why? maybe because of modifying the 
> gradle.properties 

lol , i don't understand my pc even more now

**Comment by Toffikk** [comment]
I'm testing rn on my pc , if JDK 16 building works now, if it builds a paperclip then i will change this PR from draft to ready-to-review

**Comment by Toffikk** [comment]
~~Still fails with paperclip, i need to update the shadow jar plugin in buildSrc? I think~~

EDIT : Updated

**Comment by Toffikk** [comment]
~~Need to fix lol~~

EDIT: Doesn't fail now so fixed

**Comment by Toffikk** [comment]
JDK 16 WORKS NOWWWWWW ✨👍

**Comment by toinouH** [comment]
GG

**Review by Titaniumtown — APPROVED** [review]
LGTM I'll test it later

**Pull request merged**
