### PR TITLE
Drop patch: VoxelShapes optimise Gravity Check Block Below from lithium

### PR DESCRIPTION
**Pull request by smonnnn**
This patch was was not implemented correctly and has been moved to the removed patches folder. This fixes the remaining bugs from issue #178.

### CODE REVIEW

**Comment by smonnnn** [comment]
There seem to be even more issues with collisions. Do not merge yet.

**Comment by MrIvanPlays** [comment]
alright

**Comment by duplexsystem** [comment]
Considering we have a different fix should we close this @MrIvanPlays @smonnnn ?

**Comment by MrIvanPlays** [comment]
not yet, if I drop the patch in the other pr I would close it. otherwise no

**Comment by MrIvanPlays** [comment]
Closing in favor of #183

**Pull request closed without merging**
