### PR TITLE
Implement final Hydrinity Patches

### PR DESCRIPTION
**Pull request by duplexsystem**

### CODE REVIEW

**Comment by duplexsystem** [comment]
I manged to get my hands on a copy of Hydrinity before it was deleted. I'm implementing the final changes and patches we are missing.

**Review by MrIvanPlays — CHANGES_REQUESTED** [review]
cant do proper review rn so im blocking until i can

furthermore, the whole idea of asynchronous entity tracking sucks. I suggest not to add it. we had numerous sync issues with the previous patch which had locks and everything.

**Review by MrIvanPlays — CHANGES_REQUESTED** [review]
ok here is my full review on this

async entity tracking - definitely no.
the other patch you've added - implement it properly and I may think about it.

**Comment by duplexsystem** [comment]
While I disagree about the async patch the other patch comes with drawbacks and with out the ability to easily warn users I'm going to close this. This is a zip of Hydrinity if anyone wants to update these patches or port something we missed.
[Hydrinity.zip](https://github.com/YatopiaMC/Yatopia/files/5654858/Hydrinity.zip)

**Pull request closed without merging**
