### PR TITLE
Performance enhancements (threading, hardware acceleration)

### PR DESCRIPTION
**Pull request by ishland**
Continuation of #245 

This PR has been moved to #375 

# This PR contains very experimental changes and may CORRUPT your worlds. Proceed with caution

## Hardware Acceleration
- [x] OpenCL base
- [ ] Hardware Acceleration for Noise Population
- [ ] Hardware Acceleration for Biome Population

## Threading
- [x] Threaded most of World Generation
- [x] Async Structure Generation (Single-threaded currently)
- [x] Async Feature Placements (Single-threaded currently)
- [ ] Threaded Final Generation
- [x] Threaded RegionFile & POI Data IO
- [x] Better RegionFile IO Scheduler

### CODE REVIEW

**Comment by Titaniumtown** [comment]
I tested this PRs performance at chunk gen using chunky, it's really fast!
```
seed: -8246940262100863578
chunks generated: 16129
radius: 1000

hwaccel: 136.686440678
   total time: 1:58
leaflight: 64.258964143
   total time: 4:11
timesfaster: 2.127118644x
```

**Comment by a8underscore** [comment]
https://github.com/YatopiaMC/Yatopia/pull/333/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721

there needs to be a better way to do this, that supports non-debian based distros, maybe make it a requirement to be manually installed and instead check if its installed?

**Comment by duplexsystem** [comment]
that is just a debain package. any opencl impl will work even on windows

**Comment by a8underscore** [comment]
yes but the problem is it runs "apt update" and "apt install" without any other checks

**Comment by a8underscore** [comment]
nevermind, im sorry, i didnt realize that is part of github workflows, i tought this was for the ./yatopia init & ./yatopia full, sorry my mistake

**Comment by duplexsystem** [comment]
that's just for the github build script that is configured to run on ubuntu

**Review by Titaniumtown — APPROVED** [review]
This PR has worked wonders on my server w/o any issues. I feel at least the threaded world stuff should get merged into the staging branch.

**Pull request closed without merging**
