### PR TITLE
Attempt at fixing collisions

### LINKED ISSUE #178: Oversized blocks do not have collisions.
**Expected behavior**
Entities should collide with blocks like walls

**Observed behavior**
Entities fall through wall blocks when placed on top if there are no other oversized blocks inside of the chunk before placing the wall block.

**Steps to reproduce (if known)**
Place down a wall block in a chunksection without any oversized blocks. Place an entity on top. Watch as it falls through.

**Installed plugins**
None.

**Version**
afbeelding

**Additional context**

### PR DESCRIPTION
**Pull request by MrIvanPlays**
Should fix #178
Should help with #165

### CODE REVIEW

**Comment by MrIvanPlays** [comment]
@budgidiere I FORBID you to merge this PR untill I say so

**Comment by smonnnn** [comment]
#178 is still not fixed. Entities fall through wall blocks but still collide with them horizontally when a new wall block is placed in a chunk section that had no other oversized blocks before.

**Comment by MrIvanPlays** [comment]
alright, time for some magic

**Comment by toinouH** [comment]
Now give me back my grimoire Ivan xD

**Pull request merged**
