### PR TITLE
Add more sex appeal to the TPS command

### PR DESCRIPTION
**Pull request by nkomarn**
Use Purpur's isLagging() API and combine mspt + nspt into one line.

Pretty sexy.

### CODE REVIEW

**Review by duplexsystem — APPROVED** [review]

**Review by duplexsystem — APPROVED** [review]
Sexy

**Comment by nkomarn** [comment]
The TPS command looks like this now:
image

**Comment by duplexsystem** [comment]
No it does not. It looks like this:
https://cdn.discordapp.com/attachments/743138404564467794/762419311071330324/unknown.png

**Review by PhantomG27249 — APPROVED** [review]
Seems ok

**Review by ishland — APPROVED** [review]
Seems fine for me

**Review by MrIvanPlays — APPROVED** [review]

**Pull request merged**
