### PR TITLE
optimizations

### PR DESCRIPTION
**Pull request by MrIvanPlays**

### CODE REVIEW

**Review by Titaniumtown — APPROVED** [review]
This branch has worked fine for me in my testing!

**Comment by Titaniumtown** [comment]
Better random should be used in more areas (except for world gen ofc) similar to what I did in my modified version of the patch I use in my Purpur fork: https://github.com/Titaniumtown/Purpur/blob/ver/1.16.4/patches/server/0154-Yatopia-Use-faster-random-implementation.patch

**Comment by MrIvanPlays** [comment]
> Better random should be used in more areas (except for world gen ofc) similar to what I did in my modified version of the patch I use in my Purpur fork: https://github.com/Titaniumtown/Purpur/blob/ver/1.16.4/patches/server/0154-Yatopia-Use-faster-random-implementation.patch

ill see what I can implement from this. But first I'm gonna test this cuz i've been absend for like 2 days and bud made lots of stuff

**Comment by Titaniumtown** [comment]
Ok! I talked with bud in discord yesterday and they said that they would look into implementing better random in more areas (excluding world gen). This was in #development

**Comment by Titaniumtown** [comment]
The updated better random patch LGTM!

**Pull request merged**
