### PR TITLE
Updated Upstream and Sidestream(s) (Purpur/AirplaneLite)

### PR DESCRIPTION
**Pull request by Titaniumtown**
Upstream/An Sidestream has released updates that appears to apply and compile correctly
This update has NOT been tested by YatopiaMC and as with ANY update, please do your own testing.

Purpur Changes:
5cff60d Toggle for water sensitive mobs getting damaged by... water (#161)

AirplaneLite Changes:
1b11269 This works, last time
f763e5b Keep one patch
ca87ae0 Keep empty API directory
53d0334 Rebrand as "Airplane"
1e153e0 Merge pull request #3 from DeadSteve51/patch-1
0829860 Remove actions links
12cc4d7 Adds more info to the README, mostly from the Discord
a78a63c Add new downloads URL
2a05c35 Force workflow run

### CODE REVIEW

**Review by ishland — DISMISSED** [review]

**Review by duplexsystem — CHANGES_REQUESTED** [review]
Fix Build.

**Comment by Titaniumtown** [comment]
I'm working on it rn.

**Comment by Titaniumtown** [comment]
I need to rebrand all the `AirplaneLite` stuff to `Airplane`. Give me a bit lol.

**Review by ishland — CHANGES_REQUESTED** [review]
Add Airplane licensing information

**Review by duplexsystem — DISMISSED** [review]

**Review by ishland — APPROVED** [review]

**Review by duplexsystem — APPROVED** [review]

**Pull request merged**
