### PR TITLE
Compatibility fixes

### PR DESCRIPTION
**Pull request by ishland**

### CODE REVIEW

**Review by Titaniumtown — APPROVED** [review]
needs to be merged ASAP

**Review by HookWoods — APPROVED** [review]

**Comment by krolik-exe** [comment]
Why you deleted the networking patches?

**Comment by Titaniumtown** [comment]
Because they caused issues

**Comment by toinouH** [comment]
@krolik-exe we will work on it again and make sure there is no issue this time. If you want to help us to test ping me or Hugo on Discord :)

**Pull request merged**
