### PR TITLE
Port hydrogen to Yatopia

### PR DESCRIPTION
**Pull request by HookWoods**
Ok, this is a patch that ports some fixes from Hydrogen from JellySquid3.
I adapted it to Spigot's mapping and to work on Paper. 
Like Jelly said it can actually help to reduce memory usage and will get some enhancements in the future.
All the credits go to https://github.com/jellysquid3/hydrogen-fabric for the work!

### CODE REVIEW

**Review by Titaniumtown — DISMISSED** [review]
LGTM. good work!

**Comment by duplexsystem** [comment]
Reduces memory usage as expected and the server works. Does this include the hydrogen 2.0 improvements?

**Review by duplexsystem — DISMISSED** [review]

**Comment by Titaniumtown** [comment]
> Reduces memory usage as expected and the server works. Does this include the hydrogen 2.0 improvements?

It's only some hydrogen improvements I believe. Hugo said he had some issues porting some stuff iirc.

**Comment by toinouH** [comment]
I think we could add numbers on the patch to give an idea.

**Comment by HookWoods** [comment]
Actually there is one optimisation with google things but I cant get it works and I have a fix but only work in java 9+ so can’t be ported https://github.com/jellysquid3/hydrogen-fabric/blob/1.16.x/src/main/java/me/jellysquid/mods/hydrogen/common/jvm/ClassConstructors.java

**Review by MrIvanPlays — APPROVED** [review]

**Review by Titaniumtown — APPROVED** [review]
LGTM

**Comment by PhantomG27249** [comment]
@HookWoods could you potentially implement the fix for the google stuff in such a way that the google stuff is only active when using java 9+

**Pull request merged**
