### PR TITLE
[CI-​​SKIP] Update template.md to have slightly better grammar

### PR DESCRIPTION
**Pull request by snoopdoooggyttv**
Hi!

I been messing with yatopclip and i see over in this template,
i ask a few england friends and they agree maybe of is better.

idk maybe you better, i think this is better, thank you

### CODE REVIEW

**Review by Titaniumtown — DISMISSED** [review]
LGTM

**Comment by TheArcaneBrony** [comment]
looks good to me, but what happened to that last line? 🤔

**Comment by TheArcaneBrony** [comment]
image
lol

**Comment by snoopdoooggyttv** [comment]
I saw, github bug maybe? i no change.

**Comment by TheArcaneBrony** [comment]
did you happen to remove an empty line at the end or something?

**Comment by snoopdoooggyttv** [comment]
github should show red x if it was missing.

i changed on web ui because i do not have git on pi for now, only first line was change

**Comment by Toffikk** [comment]
Why didn’t you regenerate the `PATCHES.md` ?

**Pull request merged**
