### PR TITLE
[1.16.5] Gradle 7.0.2 and updated dependencies

### PR DESCRIPTION
**Pull request by Toffikk**
edit: fixed all deprecations , and now the execution optimizations apply for paperclip task too! so building is faster

this was the last deprecation : 

```gradle
> Task :paperclip
Execution optimizations have been disabled for task ':paperclip' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/home/runner/work/Yatopia/Yatopia/Yatopia-Server/build/libs/yatopia-server-1.16.5-R0.1-SNAPSHOT.jar'. Reason: Task ':paperclip' uses this output of task ':yatopia-server:jar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
Gradle detected a problem with the following location: '/home/runner/work/Yatopia/Yatopia/Yatopia-Server/build/libs/yatopia-server-1.16.5-R0.1-SNAPSHOT.jar'. Reason: Task ':paperclip' uses this output of task ':yatopia-server:jar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#implicit_dependency for more details about this problem. This behaviour has been deprecated and is scheduled to be removed in Gradle 8.0. Execution optimizations are disabled to ensure correctness. See https://docs.gradle.org/7.0.2/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
```
and it's now fixed!!!

### CODE REVIEW

**Review by metabrixkt — DISMISSED** [review]
LGTM.

**Review by josephworks — COMMENTED** [review]
Looks good, thanks for this.

**Review by josephworks — DISMISSED** [review]

**Review by josephworks — APPROVED** [review]

**Comment by etil2jz** [comment]
any news?

**Comment by Toffikk** [comment]
i need to fix one issue that Jerry pointed out about patchCredits task failing (?)

**Comment by Toffikk** [comment]
no longer required as of #504

**Pull request closed without merging**
