### PR TITLE
Add information about performance benchmarks

### PR DESCRIPTION
**Pull request by Titaniumtown**
I did some benchmarks, and these are the results.
Screenshot from 2020-08-06 15-36-07

Tested on a raspberry pi 4, overclocked to 2ghz, 4gb of ram.

### CODE REVIEW

**Comment by duplexsystem** [comment]
if you want to help, make a bench mark section on the readme with highlights from the tests then make benchmark folder where you put testname-user.md whit more in-depth methodology and link that in the readme. also mention that these are 100% user benchmarks

**Comment by Titaniumtown** [comment]
ok, I'll do that in a bit.

**Comment by duplexsystem** [comment]
Also will you add info about the cpu usage you were getting

**Comment by jpenilla** [comment]
Would be cool if you could also compare to a Fabric server with Lithium + Phosphor installed

**Comment by Titaniumtown** [comment]
Screenshot from 2020-08-09 22-25-50

**Comment by MrIvanPlays** [comment]
@Titaniumtown do me a favor include craftbukkit in those tests

**Comment by Titaniumtown** [comment]
Ok, I can do that.

**Comment by MrIvanPlays** [comment]
Can we have an update of all the information and then we can merge this?

**Comment by notsatvrn** [comment]
yeah, updated benchmarks would be nice

**Comment by Titaniumtown** [comment]
I got a updated benchmark. I'll update the readme with it shortly

**Comment by duplexsystem** [comment]
Update on this?

**Comment by Titaniumtown** [comment]
I'm gonna rebenchmark as soon as i can.

**Comment by duplexsystem** [comment]
K

**Comment by Titaniumtown** [comment]
I'm looking for my sd card, lol.

**Comment by Titaniumtown** [comment]
I'll do this in the morning, sorry for the delay. Still can't find that SD card, lol.

**Comment by Chew** [comment]
ch/s in what context, like generating? with a chunk generator? Is the server setup the exact same (same seed, same plugins, same everything) but with different servers jars? these will be questions people will ask and you must anticipate and react accordingly.

**Comment by Titaniumtown** [comment]
Generating with Chunkmaster. I should really use the same seed. When I have time I'm gonna retest all the servers with 1 seed. The server setup is a raspberry pi 4, 4gb of ram. oc'd to 2ghz.'

I've just been very busy lately. And with school starting tomorrow, I'm going to have a lot of things to deal with.

**Comment by Chew** [comment]
Sweet, include that in the PR though so they know it's a fair comparison

**Comment by Titaniumtown** [comment]
Ok, I should also test openjdk 14 too. The current tests that I have here are a build of openjdk 15.

**Comment by Titaniumtown** [comment]
I'm going to close this PR, and make another one.

**Comment by Titaniumtown** [comment]
I moved the PR to #147

**Pull request closed without merging**
