### PR TITLE
Highly optimize VillagePlace filtering

### PR DESCRIPTION
**Pull request by MrIvanPlays**
NEEDS TESTING !!!! DO NOT USE FOR PRODUCTION UNTIL MERGED IN ver/1.16.2
NEEDS TESTING !!!! DO NOT USE FOR PRODUCTION UNTIL MERGED IN ver/1.16.2
NEEDS TESTING !!!! DO NOT USE FOR PRODUCTION UNTIL MERGED IN ver/1.16.2
NEEDS TESTING !!!! DO NOT USE FOR PRODUCTION UNTIL MERGED IN ver/1.16.2
NEEDS TESTING !!!! DO NOT USE FOR PRODUCTION UNTIL MERGED IN ver/1.16.2
NEEDS TESTING !!!! DO NOT USE FOR PRODUCTION UNTIL MERGED IN ver/1.16.2
NEEDS TESTING !!!! DO NOT USE FOR PRODUCTION UNTIL MERGED IN ver/1.16.2
NEEDS TESTING !!!! DO NOT USE FOR PRODUCTION UNTIL MERGED IN ver/1.16.2
NEEDS TESTING !!!! DO NOT USE FOR PRODUCTION UNTIL MERGED IN ver/1.16.2
NEEDS TESTING !!!! DO NOT USE FOR PRODUCTION UNTIL MERGED IN ver/1.16.2
NEEDS TESTING !!!! DO NOT USE FOR PRODUCTION UNTIL MERGED IN ver/1.16.2
NEEDS TESTING !!!! DO NOT USE FOR PRODUCTION UNTIL MERGED IN ver/1.16.2
NEEDS TESTING !!!! DO NOT USE FOR PRODUCTION UNTIL MERGED IN ver/1.16.2
NEEDS TESTING !!!! DO NOT USE FOR PRODUCTION UNTIL MERGED IN ver/1.16.2

### CODE REVIEW

**Review by duplexsystem — APPROVED** [review]
Looks good in theory

**Comment by MrIvanPlays** [comment]
we need more testers

**Comment by toinouH** [comment]
Tested:
- [x] Jake
- [ ] Unprotesting

**Comment by duplexsystem** [comment]
Is this good to merge? I've seen no issues with it.

**Comment by duplexsystem** [comment]
I tested it and found no issues.

**Pull request merged**
