### PR TITLE
Remove 2 patches that won't affect bytecode

### PR DESCRIPTION
**Pull request by mio-19**
These 2 patches just won't affect JVM bytecode

### CODE REVIEW

**Comment by duplexsystem** [comment]
A PR with this stuff go maybe better performance. Might be within margin of error. I'll do some more testing.

**Comment by duplexsystem** [comment]
Why was this closed

**Comment by Titaniumtown** [comment]
:man_shrugging:

**Comment by mio-19** [comment]
@budgidiere Because I noticed https://github.com/tr7zw/Yatopia/pull/65

**Pull request closed without merging**
