### PR TITLE
[WIP] Optimize Bukkit's MapPalette

### PR DESCRIPTION
**Pull request by metabrixkt**
Optimization for MapPalette, heavily optimized rewrite of `getDistance(Color c1, Color c2)`, `matchColor(Color color)` methods and others a bit.

Don't merge until it's tested well and no issues found.

Reopening because of changed branch.

### CODE REVIEW

**Comment by Titaniumtown** [comment]
I have a few questions:
What exactly does MapPallete do and where is it used?
What sort of benefits would this give in a real-world scenario?
Do you have any numbers on how much faster this is?

**Comment by MrIvanPlays** [comment]
> Do you have any numbers on how much faster this is?

my tests prove a decrease of 38ms from the original code to that code. we're currently working on resolving the remaining problems with the color comparisons.


> What sort of benefits would this give in a real-world scenario?

plugin drawing custom stuff on a map.


> What exactly does MapPallete do and where is it used?

matches colors from a picture to the nearest ones that minecraft allows on maps. used when a plugin wants to draw an image to get the nearest colors of every pixel.

**Comment by Titaniumtown** [comment]
@MrIvanPlays Thanks for the info!

**Comment by metabrixkt** [comment]
I'm going to open new PR for this optimisation soon.

**Pull request closed without merging**
