### PR TITLE
Fix 1.15.2 build

### PR DESCRIPTION
**Pull request by sgdc3**

### CODE REVIEW

**Comment by tr7zw** [comment]
WE DO NOT SUPPORT 1.15.2 REEEEE :trollface:

**Comment by tr7zw** [comment]
@budgidiere You can merge it, there is no java 14 build in 1.15.2.

**Comment by MrIvanPlays** [comment]
@tr7zw no we can't
image

**Comment by sgdc3** [comment]
@MrIvanPlays only owners can i guess

**Pull request merged**
