### PR TITLE
Optimise portals

### PR DESCRIPTION
**Pull request by MrIvanPlays**

### CODE REVIEW

**Comment by MrIvanPlays** [comment]
@iSilviu-debug

**Comment by iSilviu-debug** [comment]
I'm going to try them now!

**Comment by iSilviu-debug** [comment]
Hey @MrIvanPlays 
I tried the portals and the tick difference has decreased a bit. The snowballs started to lag when thrown inside only after 6 times in a row (spamming them). The portals are now random, when I return to the same portal it creates one next to me.
**Version in use:** "[19:50:39 INFO]: This server is running Yatopia version git-Yatopia-"596b1b7" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)"

**Comment by MrIvanPlays** [comment]
thanks for discovering an issue. will look at it

**Comment by iSilviu-debug** [comment]
I think instead of clearing the range to grab a nearby portal, it would be nice if it could be done in ASYNC. I hope it is possible!

**Comment by MrIvanPlays** [comment]
unfortunately the only thing we can do async is the chunks. if i make anything else async this (as of current state) broken system would break even more

**Comment by MrIvanPlays** [comment]
I tried also lowering the tick time by reducing a bunch of ops

**Comment by MrIvanPlays** [comment]
@iSilviu-debug can u try again after latest commit builds? There shouldn't be a "new portal" problem and the tick time should be a little bit lower too

**Comment by MrIvanPlays** [comment]
https://timings.aikar.co/?id=08109f7bc88f40a7b6f8730c34943b2b#timings
literally no config optimisations on a pentium I've got a 38ms compared to the timings provided in the issue, which have been optimised and were giving 54ms
not much more we can do. ill leave this open for 1 more day for further tests. otherwise those optimizations give a gain.

**Comment by iSilviu-debug** [comment]
> @ iSilviu-debug puoi riprovare dopo le ultime build di commit? Non dovrebbe esserci un problema relativo al "nuovo portale" e anche il tempo di tick dovrebbe essere leggermente inferiore

oh sorry I was sleeping at that time 🌵 🍰

**Comment by iSilviu-debug** [comment]
**I don't understand why it has the same problem**
https://timings.aikar.co/?id=6b0a4eac4e5c4c6e9683aeb66769e5dc

**Comment by MrIvanPlays** [comment]
this pr is not aiming to fix projectile lag. it aims to improve them for players.

**Comment by iSilviu-debug** [comment]
> this pr is not aiming to fix projectile lag. it aims to improve them for players.

oh sorry, _**i tried with the player himself and it also goes up to 200 tick spikes**_.
https://timings.aikar.co/?id=b2110117fdb24fa180eeecf5e818b423

**Comment by iSilviu-debug** [comment]
i noticed this: Minecraft::Distance Manager Tick (SELF)count(89)  total(23.71% 0.101s, 34.64% of tick)

**Comment by iSilviu-debug** [comment]
could it be UltraRegions?

**Comment by MrIvanPlays** [comment]
You have very good average for the time of the timings provided. Over a larger time we'd see better results.

**Comment by iSilviu-debug** [comment]
Long time of timings in nether portal stress test with one player.
**One question:** _how does the Nether portal teleport the player? Do you use PaperLib's Async?_
🌵 

https://timings.aikar.co/?id=af4ec104292044988f09307b505bcc8a

**Comment by iSilviu-debug** [comment]
_**The stress test was only tried at the last moment.**_

**Comment by MrIvanPlays** [comment]
ic very good timings.
we're preloading the chunks asynchronously.

**Comment by iSilviu-debug** [comment]
perfect 👍

**Pull request merged**
