### PR TITLE
Fix Lithium's Oversized blocks counter optimisation

### PR DESCRIPTION
**Pull request by smonnnn**
The original patch file did not update the counter correctly when blocks were placed, causing issues with collisions on oversized blocks. This patch still needs testing.

### CODE REVIEW

**Comment by smonnnn** [comment]
Issue is still not fixed, do not merge.

**Comment by smonnnn** [comment]
The issue still seems to be present, but only sometimes.

**Comment by duplexsystem** [comment]
merge or no merge?

**Comment by smonnnn** [comment]
Other issues with collisions seem to come from 0036-lithium-VoxelShapesMixin.patch, though I still need to confirm this.

**Comment by smonnnn** [comment]
Don't merge yet, I want to figure this out.

**Comment by smonnnn** [comment]
I have confirmed that it's from 0036-lithium-VoxelShapesMixin.patch being implemented incorrectly.

**Comment by smonnnn** [comment]
@budgidiere This one's good to merge, will pr with a fix for 0036 tomorrow.

**Review by MrIvanPlays — APPROVED** [review]

**Pull request merged**
